"""recreate

Revision ID: 943135202a22
Revises: 
Create Date: 2018-07-22 13:40:34.845358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '943135202a22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avocado_toast',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('invite_date', sa.DateTime(), nullable=False),
    sa.Column('expire_date', sa.DateTime(), nullable=False),
    sa.Column('link_hash', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_avocado_toast'))
    )
    op.create_table('fried_lettuce',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fried_lettuce'))
    )
    op.create_table('organic_granola',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('designer', sa.Boolean(), nullable=False),
    sa.Column('leader', sa.Boolean(), nullable=False),
    sa.Column('member', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organic_granola'))
    )
    op.create_table('kale_chips',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('nickname', sa.Text(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('salt_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['organic_granola.id'], name=op.f('fk_kale_chips_role_id_organic_granola')),
    sa.ForeignKeyConstraint(['salt_id'], ['fried_lettuce.id'], name=op.f('fk_kale_chips_salt_id_fried_lettuce')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kale_chips')),
    sa.UniqueConstraint('username', name=op.f('uq_kale_chips_username'))
    )
    op.create_index('username_index', 'kale_chips', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('username_index', table_name='kale_chips')
    op.drop_table('kale_chips')
    op.drop_table('organic_granola')
    op.drop_table('fried_lettuce')
    op.drop_table('avocado_toast')
    # ### end Alembic commands ###
